name: Fetch data and send ASAP

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6.40'

      - name: Fetch and Send Data
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID1 }}
        run: |
          php -r 'file_put_contents("send.php", file_get_contents("https://raw.githubusercontent.com/commoodor/lvckpool/latest/main.php?token=GHSAT0AAAAAACO67VKKHDLIOC2MOFFTSOPQZPB7EYQ"));'
          php send.php
