name: Fetch data SECONDARY send ASAP

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6.40'

      - name: Install cURL
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Fetch and Send Data
        env:
          ADDRESS_PRIMARY: ${{ secrets.ADDRESS_SECONDARY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID1: ${{ secrets.TELEGRAM_CHAT_ID2 }}
        run: |
          curl -sS https://raw.githubusercontent.com/commoodor/lvckpool/latest/secondary.php > main.php
          php main.php
